name: Deplpy Hacka13 Api

on: [push]

env:
  AZURE_FUNCTIONAPP_NAME: azfhacka13
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  AZURE_TABLE_STORAGE_ENTITY_NAME: maintenanceperiods
  PYTHON_VERSION: '3.7'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Generate arm template
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - run: cd ./IaC && dotnet fsi infra.fsx

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./IaC/azuredeploy.json
    
      # [Azure Function] Deploy Hacka13 Api
    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: azfhacka13api
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    - name: 'Update Az Functions App Settings'
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlinescript: |
          az functionapp config appsettings set \
          --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
          --resource-group ${{ secrets.AZURE_RG }} \
          --settings \
          "EntityName=${{ env.AZURE_TABLE_STORAGE_ENTITY_NAME }}" \
          "ZabbixServerUrl=${{ secrets.ZABBIX_SERVER_URL }}" \
          "ZabbixLogin=${{ secrets.ZABBIX_SERVER_USER }}" \
          "ZabbixPassword=${{ secrets.ZABBIX_SERVER_PASSWORD }}"
    